pipeline {
    agent any

    stages {
        stage('Установка зависимостей') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip install -r requirements.txt'
            }
        }
        stage('Запуск тестов') {
            steps {
                sh './venv/bin/python -m pytest tests/ --junitxml=test-results.xml'
            }
        }
        stage('Деплой') {
            when {
                branch 'main'
            }
            steps {
                sh './venv/bin/python setup.py sdist'
                sh 'twine upload dist/*'
            }
        }
    }

    post {
        always {
            echo 'Конвейер завершен.'
        }
    }
}
